### ISSUE TITLE
"Test file" is not working with gradle version 2.13

### ISSUE THREAD

**Issue by thmarx** [kelemen/netbeans-gradle-project#272] opened 2016-04-28 07:14 UTC
After updating to gradle 2.13 the "Test File" command is not working anymore.
I got: 
Execution failed for task ':test'.
> Could not find matching test for pattern: ...

running the tests for the whole project is still working.

I think it is related to: https://issues.gradle.org/browse/GRADLE-1553

At the command line adding the project name to the test.single property helps:
-D&lt;project&gt;test.single=

**Comment by kelemen** [comment] 2016-04-28 11:01
I can confirm the issue. To reproduce the issue, you must have a *buildSrc* project (test tasks are not needed). I cannot seem to fix it with prepending the project name (it will then execute all the tests).

Regardless fixing it requires that the plugin uses "--tests" instead of the "test.single" project property. Though it is not trivial because I do not want to break the plugin for older versions of Gradle (which did not have "--test") and if the plugin would pick the tasks right before execution (when the version of Gradle is known), the project properties dialog would be misleading (it might show different tasks by default than what will be executed).

Before fixing it, the workaround is the following: You have to adjust the "Test Single" and the "Debug Test Single" built-in tasks in the project properties to use the "--tests" form. This is done the following way:

1. Remove the "test.single" property line from the arguments.
2. Append "--tests {selected-class}" to the task list (not the arguments).

**Comment by thmarx** [comment] 2016-04-28 11:19
Thanks, the workaround works well. 

Prepending the project name is working for me to, at least from the command line.
The command has to be called from the parent project directory.
gradle :subproject:cleanTest :subproject:test -D:subproject:test.single=com/subproject/segmentation/SegmentServiceTest -c D:\workspace\parentproject\settings.gradle

**Comment by kelemen** [comment] 2016-04-28 11:51
If it works for you, you can also prepend "test.single" with "${project}:" instead of "--tests". However, it did not work for me (I tried it with a root project only).

**Comment by kelemen** [comment] 2016-05-17 18:24
Should be fixed in master.

**Closed** 2016-05-17 18:23 UTC
