### ISSUE TITLE
IDE doesn't recognize inherited methods when parent class is in a different dependency

### ISSUE THREAD

**Issue by HitkoDev** [kelemen/netbeans-gradle-project#249] opened 2015-11-29 02:05 UTC
I have a dependency ```fooDep.jar``` containing ```class Foo```, and a dependency ```barDep.jar``` containing ```class Bar extends Foo```. When I write ```bar.fooMethod();``` I get an error 
>cannot find symbol
symbol: method fooMethod() 
location: class Bar

however, the code still compiles and works the way it should. Putting both classes inside the same dependency solves the problem, but that's not an option when working with third-party dependencies.

**Comment by kelemen** [comment] 2015-11-29 22:13
This is definitely not true in general (as the title suggests). I can think of the following things:
- You failed to reload the project (from the project's context menu).
- There are multiple definitions of `Foo`.

Anyway, regardless the case, this is very unlikely to be an issue with this plugin. You should probably report this issue for NetBeans but first try deleting NB's cache: I have seen NB's cache getting corrupted in the past.

**Comment by HitkoDev** [comment] 2015-12-04 13:57
- There is only one ```Foo.class``` within all dependency packages, same goes for ```Bar.class```
- This problem occurs in exactly the same way on multiple installations of NetBeans 8.1 and 7.2
- Cleaning cache doesn't solve it
- This problem doesn't occur when I use ```fooDep.jar``` and ```barDep.jar``` in an ANT project

**Comment by kelemen** [comment] 2015-12-04 14:05
Can you share an example project with which I can reproduce your issue? Because having the implementation in another jar is fairly common and I have never experienced anything like this (and I use my plugin on a daily basis). That is, if I just do what you reported (have an implementation of an interface in different jar), I cannot reproduce your problem.

**Comment by xtracoder** [comment] 2016-01-17 14:01
Hello, just wanted to report a fresh bug like this - but it looks like this one is either close to or exactly like my case. And I have simple project to reproduce the problem (attached [nbbrk.zip](https://github.com/kelemen/netbeans-gradle-project/files/93401/nbbrk.zip) ).

Intro:
- attachment contains both MAVEN and Gradle implementation of the same staff
- there are 2 dummy projects: Server and Client
- UnitTest in Client invokes Server method, which is implemented in separate project and packaged into separate JAR. All JARs have side-by-side sources.jar
- dependency is defined as `compile "nbbrk.test:grprj-server:0.1"`

Steps to reproduce:

1. Build separately 'Server' and 'Client' (they intentionally do not have direct dependency)
2. Open ServerLibrary and set breakpoint in `someLibraryMethod()`
3. Open ClientLibraryTest and set breakpoint in the last line of `testSomeLibraryMethod()`
4. From context menu of `ClientLibraryTest` run `Debug Test File`
5. In ClientLibraryTest do Ctrl+mouse-click over `server.someLibraryMethod()` - this should navigate to source of the someLibraryMethod()

Expected result:
(4) While executing - process should firstly stop on breakpoint in `Server.someLibraryMethod()`, then in breakpoint in `ClientLibraryTest.testSomeLibraryMethod()`

Actual result:
(4) NB does not stop on breakpoint in `Server.someLibraryMethod()`, only breakpoint in `ClientLibraryTest.testSomeLibraryMethod()` does work
(5) NB opens source from the sources.JAR in local MAVEN repository, not source file from the local project. When i set breakpoint on the same line - this results in two breakpoints over that line in the  `Breakpoints` windows, what says to me that NB considers these files to be completely different and only relates to run-time class `ServerLibrary`.

What i see from that is - NB does not correlate run-time classes loaded from `server.jar` with source project for that JAR opened in that project.

The problem gets fixed when I replace dependency `compile "nbbrk.test:grprj-server:0.1"` -> `compile project(":grprj-server")` and (this is absolutely required) reload 'client' project and rebuild 'server' project. This means to me that NB in general CAN match runtime classes with source files (with dependency like `compile project(":grprj-server")`), but Gradle plugin does not correctly inform it about that (with dependency like `compile "nbbrk.test:grprj-server:0.1"`).

PS: to compare the same in MAVEN - similar project for MAVEN is also included into attached JAR. MAVEN does not have 'project' dependencies, it always uses 'artifact' notation. Resolution of the 'artifact' -> 'source project' is somehow performed by NetBeans and works correclty (i.e. - as expected).

PPS: i suspect that in original issue from _HitkoDev_ something similar may happen - i.e. NB cannot detect relation between parent and child on the source scope.

PPPS: i was testing with latest Dev build of Netbeans and plugin compiled from latest sources.

**Comment by kelemen** [comment] 2016-01-17 17:44
If you write something like this: `compile "nbbrk.test:grprj-server:0.1"`, then as far as Gradle (and NB) is concerned, this is not a project dependency. I don't think I can really make this work for you without breaking other projects. This is because I request the dependencies of the source sets themselves and at that point, I only have jar files (in a `FileCollection`).

That said, you can adjust your build script if you really want this to work in NB (it won't build dependencies automatically though). You can write something like this (in the build script of *grprj-client*):

    dependencies {
        if (project.hasProperty('evaluatingIDE') && project.property('evaluatingIDE') == 'NetBeans') {
            compile project(":grprj-server")
        }
        else {
            compile "nbbrk.test:grprj-server:0.1"
        }
    }

ps.: I recommend against using `mavenLocal` in Gradle projects ad even if you really want to use it, at least list it as the last repository otherwise it might mess up your Gradle build unexpectedly in some cases.

**Comment by JustGregory** [comment] 2016-01-17 19:41
Why not, on the ```mavenLocal```? It's incredibly useful for me. I have entirely separate trees of Gradle root projects with subprojects, that some of them depend upon the others which are ```gradlew.bat clean build install```ed to place a copy in the local cache.

Through this methodology, I can have entire platform-like chains of libraries upon which other applications, games, and such can and do depend. I would say that, my recommendation is, ```mavenLocal``` *should* be absolutely supported AND recommended.

Just my humble opinion, of course. But if you start saying one aspect of Gradle's build structure is "not recommended", then ... where does it end?

**Comment by kelemen** [comment] 2016-01-17 20:22
`mavenLocal` is supported but sometimes Maven puts incomplete artifacts into it (e.g., only a pom) and this misleads Gradle. That said, if you are listing `mavenLocal`, you should be fine.

As for recommendation, I would rather use project dependencies and maybe use other dependencies when doing release, if you don't want to release projects on the same schedule.

**Comment by JustGregory** [comment] 2016-01-17 23:07
In my case, I prefer not to list dependencies by *relative file paths* as some developers do, as projects which may be dependencies for other projects cannot be guaranteed to be in the same location on a user's computer as on my hard disk. Using ```mavenLocal``` above ```mavenCentral``` is always extremely valuable to any developer, because if the end-user checks out my dependency repo, builds and installs it, then the same should be guaranteed to work for their own ```mavenLocal``` for the dependencies.

But on the other point: "but sometimes Maven puts incomplete artifacts into it (e.g., only a pom)" -- actually, I have not ever had this happen. Ever. Is this even possible, if a ```gradlew clean build install``` is reported to succeed? If something fails, possibly, but in such a case I *know* there is a problem to correct, and I do. But, succeeding a build and install could possibly leaves incomplete artifacts?

**Comment by kelemen** [comment] 2016-01-17 23:17
I don't think either Maven's or Gradle's install can do such a thing. The main way it can happen (I believe, though I don't usually use Maven nowadays), is if downloading the dependencies fails partially. I have seen a couple of reports in the past where users were wondering why their dependencies does not get downloaded.

Anyway, `mavenCentral` is completely fine to be used, it is just `mavenLocal` which is only provided (as far as I know) for better interoperation with Maven projects. Regardles, there is not much harm in listing *mavenLocal* as the last repository (unless you release your project and keep building it with the same version) and that is safe. It is just, that your case (though you can keep doing if you think otherwise) is not really the intended one. I would rather use project dependencies if I were you, that is a lot more convenient. If you need explicit versions on release, then specify that only for release (you can script it whatever way you see the best).

**Comment by xtracoder** [comment] 2016-01-18 07:06
Few points from my side:

* I think, `mavenLocal` is a 'red herring' in context of this issue. The only difference between mavenLocal/mavenCentral/jCenter is that first one already has all artifacts locally, other ones needs them to be downloaded into local cache - after that they are 'the same'. The main thing here is - get artifact file with known version tag.

* Recomendation to use `project` dependencies instead of `artifact` dependencies is not workable for the cases when projects are completely unrelated, they are just loaded together into same instance of NetBeans - there is no way make 'project' dependency. `project`  dependency used in my sample is 'artificial' and is intended just to check the difference in functional behavior between different dependency types.

* "_If you write something like this: compile "nbbrk.test:grprj-server:0.1", then as far as Gradle (and NB) is concerned, this is not a project dependency. I don't think I can really make this work for you without breaking other projects. This is because I request the dependencies of the source sets themselves and at that point, I only have jar files (in a FileCollection)._"

I think this not a major problem and can be 'fixed' in a following way:

1. Each artifact dependency results in a file with a fixed name, e.g.: grprj-server-0.1.jar

2. Each project has outputs, which may generate that file, you can get them using code below (not sure if it is really efficient)

3. So ... the only thing to be done when you get project with artifact dependencies is scan (actually, look into some reverse artifact->project dictionary) for other loaded projects and check if there is anyone that generates artifact file with the same file name. After that NB should be somehow informed that 'jar from this location' has sources loaded in 'that project'.

Script to output list of generated artifacts per project (using different technics). Invoked by `gradle info`
```
allprojects {
    afterEvaluate { project ->
        task info {
            println ''
            println 'project:' + project.name
            
            def jar = project.tasks.findByName('jar')

            println 'jar:'
            println ' ... -> ' \
                + (jar == null ? null : jar.outputs.files.files)

            def archives = project.configurations.findByName('archives')
            
            println 'project.archives:'
            if( archives != null ) {
                archives.allArtifacts.files.each { atf ->
                    println ' ... -> ' + atf
                }
            }
        }
    }
}
```

**Comment by kelemen** [comment] 2016-01-18 08:14
The `mavenLocal` was just my side note, it - of course - does not affect this issue.

To be honest, the plugin already relies on something similar to detect dependencies across projects (because on the source set, I only see the jar file of the dependency), though matching of files is done with path included (and only between projects of the same multi-project build). Matching jar files ignoring path seems to be an interesting idea, though I won't make it a default behaviour. That is, if I implement it, it has to be configured explicitly. By the way, this is not necessarily this simple because versions might change, especially if someone uses the time in the version.

**Comment by xtracoder** [comment] 2016-01-18 09:39
If you are talking about auto-generated version number with timestamp in it - i think such cases can be ignored because ...
- its nonsense - i'm not aware about any Java versioning system having such approach as standard. Some do [use dates](http://mvnrepository.com/artifact/com.google.javascript/closure-compiler/v20151216) in their versioning system,  but this is absolutely OK - this is not tag which changes with each triggered build.
- if such cases do exist in real practice - that 0.001% of users will have to find some tricky way to work with their tricky build environment.

**Comment by kelemen** [comment] 2016-01-18 11:49
I don't think it is as uncommon as you say. For example, [Gradle uses](https://github.com/gradle/gradle/blob/e396465d86868791269a8251889eee8ffa8b0d40/gradle/versioning.gradle) such for its snapshot builds.

**Comment by xtracoder** [comment] 2016-02-21 20:22
Since problem of breakpoints not working in cross-project environment has become a work stoppage to me,  I decided to fix it for myself. After 1 day of trying to grasp all levels of abstractions coming from netbeans, grade and this plugin I finally was able to change few lines of code :) - [here are they are](https://github.com/xtracoder/netbeans-gradle-project/commit/ea4eaa60b46abe36fa2e30503ddec1b6aed2eab6). Feel free to copy-paste if seems useful.

Few notes: 

- I did not notice usage of JarOuputs coming from Gradle in code of this plugin, therefore identification of the matching Gradle project for a Jar from dependency is performed by lookup for presence of `<projectDir>/build/libs/<artifact-id-n.n.n.jar>` file. More correct matching should be based on JarOutputs, but this it too much for me.

- Because i'm not very familiar with process of loading of projects in NB - i did not implement any checks that reflect changes in current project group, i.e. if target dependency project is closed or something similar. Just functionality minimally required for me is implemented.

- Implementation is far from production quality - just works for me.

**Comment by kelemen** [comment] 2016-02-22 12:17
The main reason why you probably could not make use of `JarOutputs` there is that this code (or rather, something similar) should be in `GradleClassPathProvider` instead. Because the parsing is only done on project (re)load, so other projects should have already been loaded for this to work.

The best way - I can think of - implementing this is to register the *jar names* to *(project, JarOutput)* on project open, then `GradleClassPathProvider` listens for changes in this global "map" and adjusts the classpath accordingly.

**Comment by kelemen** [comment] 2016-05-17 18:29
This should be fixed in master but is disabled by default. To enable project dependency lookup based on jar name: Select the appropriate checkbox in the global settings: Options/Misc./Gradle/Other.

**Closed by kelemen** 2016-05-17 18:29 UTC
