### ISSUE TITLE
Cannot load gradle project on Windows

### ISSUE THREAD

**Issue by admiral0** [kelemen/netbeans-gradle-project#182] opened 2015-02-19 09:12 UTC
Cannot load project in windows. Will pop an issue as soon as starts loading. OS is windows 8. NB 8.0.2. Java 1.7

ST.

```
Stack trace:
    org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle installation 'D:\Programmi\Gradle\gradle-2.3'.
     at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:55)
     at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
     at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     at java.lang.Thread.run(Thread.java:724)
     at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
     at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:46)
     at org.netbeans.gradle.model.GenericModelFetcher.getModels(GenericModelFetcher.java:166)
     at org.netbeans.gradle.project.model.NbGradle18ModelLoader$ProjectModelFetcher.getModels(NbGradle18ModelLoader.java:375)
     at org.netbeans.gradle.project.model.NbGradle18ModelLoader.loadModels(NbGradle18ModelLoader.java:80)
     at org.netbeans.gradle.project.model.GradleModelLoader.loadModelWithProgress(GradleModelLoader.java:503)
     at org.netbeans.gradle.project.model.GradleModelLoader.access$600(GradleModelLoader.java:63)
     at org.netbeans.gradle.project.model.GradleModelLoader$6.run(GradleModelLoader.java:372)
     at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:36)
     at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:23)
     at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:126)
     at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
     at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
     at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
     at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:905)
     at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:884)
     at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:798)
     at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:813)
     at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:847)
     at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
     at java.lang.Thread.run(Thread.java:724)
    Caused by: org.gradle.api.GradleException: Could not determine the class-path for class org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.
     at org.gradle.tooling.internal.provider.ClasspathInferer.find(ClasspathInferer.java:128)
     at org.gradle.tooling.internal.provider.ClasspathInferer.getClassPathFor(ClasspathInferer.java:52)
     at org.gradle.tooling.internal.provider.ClientSidePayloadClassLoaderRegistry$1.visitClass(ClientSidePayloadClassLoaderRegistry.java:48)
     at org.gradle.tooling.internal.provider.PayloadSerializer$1.writeClassLoader(PayloadSerializer.java:77)
     at org.gradle.tooling.internal.provider.PayloadSerializer$1.writeClass(PayloadSerializer.java:68)
     at org.gradle.tooling.internal.provider.PayloadSerializer$1.writeClassDescriptor(PayloadSerializer.java:56)
     at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1279)
     at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1228)
     at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1424)
     at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
     at org.gradle.tooling.internal.provider.PayloadSerializer.serialize(PayloadSerializer.java:82)
     at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:98)
     at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:171)
     at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection.run(CancellableConsumerConnection.java:52)
     at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:57)
     at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:88)
     at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
     at org.gradle.tooling.internal.consumer.connection.LoggingInitializerConsumerActionExecutor.run(LoggingInitializerConsumerActionExecutor.java:44)
     at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
     at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     ... 1 more
    Caused by: org.gradle.api.GradleException: Cannot determine classpath for org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter from codebase 'jar:file:/C:/Users/Username/AppData/Roaming/NetBeans/8.0.1/modules/ext/gradle-tooling-api-2.1.jar!/'.
     at org.gradle.internal.classloader.ClasspathUtil.getClasspathForClass(ClasspathUtil.java:68)
     at org.gradle.tooling.internal.provider.ClasspathInferer.find(ClasspathInferer.java:83)
     ... 23 more
```

**Comment by kelemen** [comment] 2015-02-19 09:22
This is a duplicate of #178. Sadly, a bug in Gradle prevents Gradle 2.3 to be used with NetBeans. The bug is already fixed in Gradle's nightly build.

**Closed by kelemen** 2015-02-19 09:22 UTC
Labels: duplicate
