### ISSUE TITLE
Opening an Ant project after a Gradle project seems to break NetBeans functionality

### ISSUE THREAD

**Issue by qcsoftware513** [kelemen/netbeans-gradle-project#214] opened 2015-06-05 16:10 UTC
It appears if I open my main gradle project and then later open an ant project (older project prior to migrating to gradle), then i can no longer use certain functionality in my gradle project.  i used the following steps to reproduce:
 1. Start new user dir
 2. Open gradle project
   - Refactoring works fine at this point
 3. Open ANT project
 4. Close ANT project
   - Refactoring no longer works.

Not sure if this is NetBeans or the plugin causing the problem.  It seems i can clear the problem by wiping out my config directory and reloading my settings.

**Comment by kelemen** [comment] 2015-06-06 20:33
This is not enough info. Can you create an example with which I can reproduce the issue? The problem could be that the Ant project takes ownership of a directory of the Gradle project. By the way, closing a project has little immediate effect in NB. That is, project loading is not necessary due to a project being opened.

**Comment by qcsoftware513** [comment] 2015-06-06 20:58
I will work on this next week.  Things are kind of busy right now, but I’ll see what we can put together.

Mike

**Closed** 2016-09-28 09:38 UTC
