### ISSUE TITLE
Applying only the "java-base" plugin causes NPE during project load

### ISSUE THREAD

**Issue by dremon** [kelemen/netbeans-gradle-project#298] opened 2016-10-13 11:30 UTC
In the latest plugin version 1.3.9 loading of the project which doesn't have 'java' plugin in the root script causes NullPointerException

```
java.lang.NullPointerException
	at org.netbeans.gradle.project.java.model.JavaParsingUtils.getJarOutputs(JavaParsingUtils.java:253)
	at org.netbeans.gradle.project.java.model.JavaParsingUtils.parseModules(JavaParsingUtils.java:237)
	at org.netbeans.gradle.project.java.JavaExtensionDef.parseFromNewModels(JavaExtensionDef.java:76)
	at org.netbeans.gradle.project.java.JavaExtensionDef.parseModelImpl(JavaExtensionDef.java:109)
	at org.netbeans.gradle.project.java.JavaExtensionDef.parseModel(JavaExtensionDef.java:120)
[catch] at org.netbeans.gradle.project.extensions.NbGradleExtensionRef.parseModel(NbGradleExtensionRef.java:115)
	at org.netbeans.gradle.project.model.NbGradle18ModelLoader$ProjectModelParser.parseModel(NbGradle18ModelLoader.java:264)
	at org.netbeans.gradle.project.model.NbGradle18ModelLoader$ProjectModelParser.parseModel(NbGradle18ModelLoader.java:216)
	at org.netbeans.gradle.project.model.NbGradle18ModelLoader.loadModels(NbGradle18ModelLoader.java:81)
	at org.netbeans.gradle.project.model.DefaultGradleModelLoader.loadModelWithProgress(DefaultGradleModelLoader.java:550)
	at org.netbeans.gradle.project.model.DefaultGradleModelLoader.access$1500(DefaultGradleModelLoader.java:68)
	at org.netbeans.gradle.project.model.DefaultGradleModelLoader$7.run(DefaultGradleModelLoader.java:414)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:35)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:22)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:125)
	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:919)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:898)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:815)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:827)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:861)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kelemen** [comment] 2016-10-13 13:10
Can you provide a sample project with which I can reproduce the problem because it is certainly not because there is project which does not have the 'java' plugin applied. Does the notification window have any issue reported?

**Comment by dremon** [comment] 2016-10-13 13:23
Yes, here is the minimal script. Notification window has java.lang.NullPointerException (with the details I posted above).

```
apply plugin: 'java-base'

sourceSets {
	doc.resources.srcDir 'doc'
}

```

**Comment by kelemen** [comment] 2016-10-13 13:26
I see, you are only applying the java-base plugin. I have never used java-base in itself, I will see what can / should be done in this case. Anyway, may I ask why are you applying only the java-base plugin?

**Comment by sajbear** [comment] 2016-10-13 13:26
I have the same issue, my projekt is a standard Libgdx project. 
The android part of the projekt works and shows the source files in the tree. But the core projekt doesn't

I tried to download and generate a totaly fresh projekt with the Libgdx Setup App and imported that projekt. Same error! You can use that as a base!

I used NetBeans 8.1 btw. Hope it helps!

**Comment by dremon** [comment] 2016-10-13 13:28
Well it's a root project which doesn't have any sources so there is no need to load a java plugin. It only contains docs/scripts and subprojects.

Subprojects do apply the java plugin however.
Used to work in the older version.

**Comment by dremon** [comment] 2016-10-13 13:29
The reason 'java-base' is loaded is for the 'clean' task.

**Comment by kelemen** [comment] 2016-10-13 13:29
You can use the "base" plugin instead of "java-base" for that purpose (that is what I do).

**Comment by dremon** [comment] 2016-10-13 13:31
'base' doesn't define sourceSets and I'd like some folders to be visible in the IDE.

**Comment by dremon** [comment] 2016-10-13 13:36
I think it only happens when you have sourceSets defined. Simply applying the java-base doesn't trigger this error.

**Comment by kelemen** [comment] 2016-10-13 13:41
Yes, you won't have any problem when you have zero source sets because the Java extension [will be disabled](https://github.com/kelemen/netbeans-gradle-project/blob/8c928f577c048980f2731e33f6d1326996184a13/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/java/model/JavaParsingUtils.java#L211-L216) in that case. Also I find it very strange that it used to work because the bug is clear and it worked the same way in earlier version as well.

**Comment by sajbear** [comment] 2016-10-13 13:50
I downloaded 1.3.8.1 source and compiled my own nbm as a workaround.

**Comment by kelemen** [comment] 2016-10-13 13:53
You don't have to rebuild for older versions: Previous versions are in my BinTray repo. E.g.: http://dl.bintray.com/kelemen/maven/com/github/kelemen/netbeans-gradle-plugin/1.3.8.1/netbeans-gradle-plugin-1.3.8.1.nbm

**Comment by kelemen** [comment] 2016-10-13 17:13
The issue was added when the jar name based project dependency detection was added.

This should be fixed in master now. Can I ask you to verify the fix?

**Closed by kelemen** 2016-10-13 17:13 UTC

**Comment by dremon** [comment] 2016-10-13 20:07
I can confirm that it works now.
