### ISSUE TITLE
Projects fail to load with Gradle 2.3-rc-1

### ISSUE THREAD

**Issue by swpalmer** [kelemen/netbeans-gradle-project#178] opened 2015-02-02 20:09 UTC
Seems to have trouble finding the tooling APIs.

**Comment by kelemen** [comment] 2015-02-02 22:30
Thanks for the report. I can reproduce the issue myself. Though, I have no idea the source of the problem yet.

**Comment by wvreeven** [comment] 2015-02-16 09:17
Here is the stacktrace shown in Netbeans when using gradle 2.3:

Issue 1
--------

  Requested project: <project name>

  Stack trace:
    org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle installation '<gradle installation dir>'.
    	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:55)
    	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
    	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
    	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:46)
    	at org.netbeans.gradle.model.GenericModelFetcher.getModels(GenericModelFetcher.java:166)
    	at org.netbeans.gradle.project.model.NbGradle18ModelLoader$ProjectModelFetcher.getModels(NbGradle18ModelLoader.java:375)
    	at org.netbeans.gradle.project.model.NbGradle18ModelLoader.loadModels(NbGradle18ModelLoader.java:80)
    	at org.netbeans.gradle.project.model.GradleModelLoader.loadModelWithProgress(GradleModelLoader.java:503)
    	at org.netbeans.gradle.project.model.GradleModelLoader.access$600(GradleModelLoader.java:63)
    	at org.netbeans.gradle.project.model.GradleModelLoader$6.run(GradleModelLoader.java:372)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:36)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:23)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:126)
    	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
    	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
    	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
    	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:905)
    	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:884)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:798)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:813)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:847)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.gradle.api.GradleException: Could not determine the class-path for class org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.
    	at org.gradle.tooling.internal.provider.ClasspathInferer.find(ClasspathInferer.java:128)
    	at org.gradle.tooling.internal.provider.ClasspathInferer.getClassPathFor(ClasspathInferer.java:52)
    	at org.gradle.tooling.internal.provider.ClientSidePayloadClassLoaderRegistry$1.visitClass(ClientSidePayloadClassLoaderRegistry.java:48)
    	at org.gradle.tooling.internal.provider.PayloadSerializer$1.writeClassLoader(PayloadSerializer.java:77)
    	at org.gradle.tooling.internal.provider.PayloadSerializer$1.writeClass(PayloadSerializer.java:68)
    	at org.gradle.tooling.internal.provider.PayloadSerializer$1.writeClassDescriptor(PayloadSerializer.java:56)
    	at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1282)
    	at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1231)
    	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1427)
    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    	at org.gradle.tooling.internal.provider.PayloadSerializer.serialize(PayloadSerializer.java:82)
    	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:98)
    	at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:171)
    	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection.run(CancellableConsumerConnection.java:52)
    	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:57)
    	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:88)
    	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
    	at org.gradle.tooling.internal.consumer.connection.LoggingInitializerConsumerActionExecutor.run(LoggingInitializerConsumerActionExecutor.java:44)
    	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
    	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	... 1 more
    Caused by: org.gradle.api.GradleException: Cannot determine classpath for org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter from codebase 'jar:file:<user home>/.netbeans/8.0.2/modules/ext/gradle-tooling-api-2.1.jar!/'.
    	at org.gradle.internal.classloader.ClasspathUtil.getClasspathForClass(ClasspathUtil.java:68)
    	at org.gradle.tooling.internal.provider.ClasspathInferer.find(ClasspathInferer.java:83)
    	... 23 more

**Comment by kelemen** [comment] 2015-02-16 09:50
Looking more at this issue, I believe that this is a bug in Gradle and reported it on the [Gradle forums](http://forums.gradle.org/gradle/topics/gradle-2-3-tooling-api-class-loading-error-for-build-action).

**Comment by eskatos** [comment] 2015-02-18 10:02
:+1: 
Voted in gradle forums and JIRA (https://issues.gradle.org/browse/GRADLE-3245)

**Comment by WillBDaniels** [comment] 2015-02-18 18:16
Voted! thanks for looking into this and getting the issue raised.

**Comment by kelemen** [comment] 2015-02-19 00:08
The issue seems to be fixed in Gradle 2.4-20150218230021+0000. Sadly, this means that Gradle 2.3 will never work with NetBeans (since the bug is in Gradle).

**Closed by kelemen** 2015-02-19 00:08 UTC
Labels: bug, wontfix

**Comment by kelemen** [comment] 2015-02-26 08:31
Just for the reference, if someone really wants to use Gradle 2.3 with NetBeans: Setting "Build script evaluation strategy" to "Idea plugin based" will work but in this case lots of custom settings in the build script will not be recognised.

**Comment by kelemen** [comment] 2015-03-01 21:55
Adjusted the plugin to automatically revert to using the old strategy when trying to use Gradle 2.3 (with an appropriate warning).

**Comment by hexture2** [comment] 2015-08-12 17:05
In netbeans 8.0.1 I  updated the 
tools-> Gradle Support

and the errors are gone thanks!

**Comment by hexture2** [comment] 2015-08-12 17:20
From netbeans 8.0.1 I did 
help -> check for updates 
and was able to move up to 8.0.2
and was at least able to load my existing gradle 2.3 project. with some warnings.
thanks,

{note we had to move back to gradle 2.3 since 2.4 didn't work with Team City build :) }

**Comment by ray-print** [comment] 2016-02-21 05:33
@kelemen THANK YOU for that tip. Was having problems with Gradle 2.11 and Netbeans 7.3.1 and that fixed it.

**Comment by kelemen** [comment] 2016-02-21 12:27
@ray-print  What was your problem exactly? I can load projects using Gradle 2.11 without any problem.

**Comment by ray-print** [comment] 2016-02-22 06:34
If I remember, first I got the "Cannot determine classpath" error, then the "could not run build action" error. The former was solved by setting some configuration option correctly, the latter by setting "Build script evaluation strategy" to "Idea plugin based" as you suggested. I had a set of problems with Gradle, most of which were probably caused because I don't really understand it yet, and because my computer is old (so I'm stuck at Java 1.6 and old versions of Gradle/Netbeans/Eclipse).

**Comment by kelemen** [comment] 2016-02-22 12:24
If you can reproduce the problem, can you open a separate issue with the stack trace of the error included?

**Comment by ray-print** [comment] 2016-02-23 19:47
Can't easily reproduce it.
If it comes up again I will open up a new issue.

**Comment by ray-print** [comment] 2016-02-24 20:15
What do you know, it is reproducible now. Filed as: #265
