### ISSUE TITLE
G4NB can't find reports when trying to draw/update the TestRests window (when results in sub-dir)

### ISSUE THREAD

**Issue by fwelland** [kelemen/netbeans-gradle-project#200] opened 2015-05-08 16:02 UTC
So I got this gradle snippet: 
```
drivers.each { driver ->
    task "${driver}test"(type: Test) {
        println("Created task: ${driver}test")
        if (parallel) {
            maxParallelForks = Runtime.runtime.availableProcessors()
        }
        testClassesDir = sourceSets.test.output.classesDir
        classpath = sourceSets.test.runtimeClasspath
        reports {
            html.destination = reporting.file("$name/tests")
            junitXml.destination = file("$buildDir/test-results/$name")
            html.enabled = true
        }
      //....
}
```

G4NB works ok with this -- but in the test-single case the results are in an xml tucked underneath the typical test-results directory.    And when NB and/or G4NB try to update the Test Results window, it doesn't seem to look in sub dirs to locate a matching XML and draw results. 

Not clear if something could actually done about this as implied from the above, there maybe more than one subdir in test-results.  Those could have had the same test results xml file for the test run for the different runs(i.e. same test, different browser, different results xml). 

Or maybe there is something I can do on my side -- I guess I can change the results.xml to not be dumped in sub-dirs but in test-results and (somehow) add the browser name to the pattern used to make the results  xml file.....

**Comment by kelemen** [comment] 2015-05-08 19:45
The plugin does not search for the test output xml rather it reads it from the `reports.junitXml.destination` property of the Test task. The problem is that the plugin believes that you are running the `test` task (i.e., the plugin assumes that you are running the `${test-task-name}` task). In your case, this is not true.

I don't think, there is a reasonable way for you to fix this. The only thing you could do is to have the same output for those test tasks as the `test` task and I doubt that this is an option for you. So, currently the only thing you can do is to see the generated html output in the browser (to be honest I prefer that over NBs test results window). But yes, this should be fixed.

**Comment by kelemen** [comment] 2015-05-19 15:58
This should now be fixed in master.

**Comment by fwelland** [comment] 2015-05-20 18:36
I pulled master and rebuilt.     It didn't  work.     Here are a couple of lines from my ide log: 

INFO [org.netbeans.gradle.project.tasks.GradleTasks]: Executing: gradle :acceptance-test:cleanAcceptanceTest :acceptance-test:firefoxacceptanceTest, Args = [-DfirefoxacceptanceTest.single=tests/ProtectAgainstDirectAccessTest, -c, /home/fwelland/JavaStuff/NetBeansProjects/pinapps-rebuild/settings.gradle], JvmArg = []
INFO [org.netbeans.gradle.project.tasks.GradleTasks]: Applying init-script: TmpFileRef{/tmp/nb-gradle-plugin-fwelland/task-init-script-f250cb0e47d493e95a15edd0dac66dde.tmp}
WARNING [org.netbeans.gradle.project.java.test.TestXmlDisplayer]: Could not find output for test task "acceptanceTest" in /home/fwelland/JavaStuff/NetBeansProjects/pinapps-rebuild/acceptance-test/build/test-results

The results file does exist and it lives in:   

/home/fwelland/JavaStuff/NetBeansProjects/pinapps-rebuild/acceptance-test/build/test-results/firefoxacceptanceTest


Is there something I am doing wrong?

**Comment by kelemen** [comment] 2015-05-20 18:58
No, you are doing it right, I just forgot about absolute path being specified as a task name.

**Comment by kelemen** [comment] 2015-05-20 19:40
Hopefully this should fix your issue now. Thanks for trying out before release.

**Closed** 2015-05-20 19:39 UTC
Labels: enhancement

**Comment by fwelland** [comment] 2015-05-20 19:53
Totally Worked!!!!!  THANKS!!!

(agreed the html reports are better; for me , the NB test results window is handy while authoring a test.)
