### ISSUE TITLE
Go to type (Ctrl + O) doesn't work. Find usages (Alt + F7) doesn't work.

### ISSUE THREAD

**Issue by Apertum** [kelemen/netbeans-gradle-project#310] opened 2017-01-04 17:42 UTC
Nice job! Great plugin. But where are some problems.

NB8.0 or NB 8.2. Go to type (Ctrl + O) doesn't work. Types under gradle couldnt be searched. Find usages (Alt + F7) doesn't work. The same behaviour.
Types under ANT can be searched without any problems. What to do? I would help to improve plugin if I will be able to.

Thanks for plugin.

**Comment by kelemen** [comment] 2017-01-05 19:36
It should work, I have never seen it fail. Can you tell me what exactly you are doing or even share a project with which you are having a problem?

**Comment by Apertum** [comment] 2017-01-05 20:22
1. NB8.2 was downloaded and installed
2. Plugin was installed by default way in NB
3. Project was opened.
4. Shortcuts are working but unfortunately classes in this gradle project aren`t founded. Only classes from another ANT projects were founded as expected.

It is in my opensource project. In some days I will share changes for gradle and everybody can check this situation. Maybe my build.gradle isn`t correct or something else.

**Comment by kelemen** [comment] 2017-01-05 20:43
If the project builds from the command line, I would expect it to work in NB (except for some extremely custom build).

**Comment by Hillkorn** [comment] 2017-01-06 11:45
@Apertum By gradle classes you mean classes under org.gradle.api for example? Or just java classes in your src/main/java/* ?
I did a lot of custom stuff and never had any problems. Even the autodetection for projects as dependencies works perfectly as long as the version matches.

**Comment by wadechandler** [comment] 2017-01-06 18:18
Same for me. I even have alternate source directories for both .java and
.groovy files, tests, sources, etc, and the IDE and shortcuts find the
files. Maybe look in your logs and attach or give some other details on the
gradle build, structure, and setup. Even better would be to create a Github
repo showing the issue to help us replicate it.

Thanks

Wade

**Comment by Apertum** [comment] 2017-01-06 18:40
Project here https://bitbucket.org/Apertum/qsystem/src
Everybody can clone the repo and check search or find usages. On monday I'll try test this project on another computer.

I talk about my classes. All my classes in folders 'src' and 'reports'. Gralde is building all and NB can run and debug without any problems.

**Comment by Hillkorn** [comment] 2017-01-09 08:33
@Apertum I checked out your repo and had the same issue but it seems that the src/ru/apertum/qsystem/server/model/calendar/TableCell.java file is the problem. The name of the file, class and constructor contain a special character that caused issues for me.
But i still have the same problem in your project as you have. Is there a reason why you customize your structure that java and resource share the same folder?

**Comment by Apertum** [comment] 2017-01-09 13:43
Much more problems. NB8.2 underline by red all imports of my classes in source code as unknown classes. NB can not understand including classes from same project. Gradle script is working well without any problems but "Go to type", "Find usages" and included types aren't work in NB.

**Comment by Hillkorn** [comment] 2017-01-09 13:47
The Gradle script didn't worked for me because of the special character
issue that is hidden in the tablecell class. I think you use Windows right?
I'm using Linux and that is not that friendly like Windows for filenames.

Evgeniy Egorov <notifications@github.com> schrieb am Mo., 9. Jan. 2017,
14:43:

**Comment by Apertum** [comment] 2017-01-09 13:50
special character in TableCell.java is something because of codepages in different OS or etc. Just rename or rewrite.

**Comment by Hillkorn** [comment] 2017-01-09 13:54
I did and then it worked but I was able to resolve them sometimes as I
changed the script a bit but I was kind of unstable because it didn't
worked always. In general I would recommend to adapt your source structure
to the one that Gradle and others are using.

Evgeniy Egorov <notifications@github.com> schrieb am Mo., 9. Jan. 2017,
14:50:

**Comment by Apertum** [comment] 2017-01-09 14:05
I understood that. But this situation looks like not so pleasant for NB+Gradle. Is this plugin supported now by author? Is where a chance to fix this issue?

**Comment by kelemen** [comment] 2017-01-09 21:47
Sorry for not responding but I have missed your comment. I think, I have good guess what could fool NetBeans. You have the same source roots with different filters and probably NB just picks one of them. I will see what I can do about it.

As a workaround for now, you can replace your *sourceSets* block with this:
    boolean nb = project.hasProperty('evaluatingIDE') && project.property('evaluatingIDE') == 'NetBeans'
    sourceSets {
        main {
            java {
                srcDirs = ['reports', 'src' ]
                if (!nb) {
                    includes =  [ '**/*.java' ]
                }
            }
            resources {
                srcDirs = ['reports', 'src' ]
                if (!nb) {
                    excludes =  [ '**/*.form', '**/*.orig', , '**/*.java' ]
                }
            }
        }
    }

This of course have a bad side effect: Every file will be visible under every node.

**Comment by kelemen** [comment] 2017-01-09 22:38
Should be fixed in master. Can you try building the plugin from the sources and see if it solves your issue?

**Comment by Apertum** [comment] 2017-01-10 09:15
Cool. I'll try but not right now. Maybe in few days.

**Comment by Apertum** [comment] 2017-01-11 13:34
@kelemen  Could you help me to build the plugin?
I run command "gradle build"
Result:
`
...
:netbeans-gradle-default-models:build UP-TO-DATE
:netbeans-gradle-plugin:configureCompileJava
:netbeans-gradle-plugin:compileJava UP-TO-DATE
:netbeans-gradle-plugin:processResources UP-TO-DATE
:netbeans-gradle-plugin:mergeProperties UP-TO-DATE
:netbeans-gradle-plugin:classes UP-TO-DATE
:netbeans-gradle-plugin:generateModuleManifest
:netbeans-gradle-plugin:jar
:netbeans-gradle-plugin:sourcesJar UP-TO-DATE
:netbeans-gradle-plugin:assemble
:netbeans-gradle-plugin:configureCompileTestJava
:netbeans-gradle-plugin:compileTestJava UP-TO-DATE
:netbeans-gradle-plugin:processTestResources UP-TO-DATE
:netbeans-gradle-plugin:testClasses UP-TO-DATE
:netbeans-gradle-plugin:test

org.netbeans.gradle.project.java.query.AutoJavaBinaryForSourceQueryTest > testFindBinaryOfZipSource FAILED
    java.lang.AssertionError at AutoJavaBinaryForSourceQueryTest.java:37

org.netbeans.gradle.project.java.query.AutoJavaSourceForBinaryQueryTest > testFindZipSource FAILED
    java.lang.AssertionError at AutoJavaSourceForBinaryQueryTest.java:37

org.netbeans.gradle.project.java.query.GradleSourceForBinaryQueryTest > testSourcesForClassesDirs FAILED
    java.lang.AssertionError at GradleSourceForBinaryQueryTest.java:45
        Caused by: java.lang.AssertionError at GradleSourceForBinaryQueryTest.java:79

org.netbeans.gradle.project.properties.ConfigXmlUtilsTest > testSaveDoesNotChangeASingleCharacterTaskArgsHaveValues FAILED
    java.lang.AssertionError at ConfigXmlUtilsTest.java:176

org.netbeans.gradle.project.properties.ConfigXmlUtilsTest > testSaveDoesNotChangeASingleCharacterTaskArgsHaveNoValues FAILED
    java.lang.AssertionError at ConfigXmlUtilsTest.java:176

org.netbeans.gradle.project.query.GradleCacheSourceForBinaryQueryTest > testOldCacheFormat FAILED
    java.lang.AssertionError at GradleCacheSourceForBinaryQueryTest.java:37

org.netbeans.gradle.project.query.GradleCacheSourceForBinaryQueryTest > testNewCacheFormat FAILED
    java.lang.AssertionError at GradleCacheSourceForBinaryQueryTest.java:37

org.netbeans.gradle.project.query.GradleHomeSourceForBinaryQueryTest > testFindSourceOfStandardLib FAILED
    java.lang.AssertionError at GradleHomeSourceForBinaryQueryTest.java:53

org.netbeans.gradle.project.query.GradleHomeSourceForBinaryQueryTest > testFindSourceOfStandardLibInSubDir FAILED
    java.lang.AssertionError at GradleHomeSourceForBinaryQueryTest.java:53

250 tests completed, 9 failed, 1 skipped:test > 250 tests completed, 9 failed, 1 skipped
:netbeans-gradle-plugin:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':netbeans-gradle-plugin:test'.
> There were failing tests. See the report at: file:///D:/work/qs/netbeans-gradle-project-master/netbeans-gradle-plugin/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.583 secs


D:\work\qs\netbeans-gradle-project-master>
`

**Comment by kelemen** [comment] 2017-01-11 15:48
It should build out of the box and it does on Travis. So, I would need the test errors. For now you can skip tests by passing *-xtest*.

**Comment by Apertum** [comment] 2017-01-12 07:48
It works! I built without tests _-xtext_, reinstalled the plugin.

Nice support. Thank you.

About failure test. I just downloaded master as ZIP, unpacked it, run 'gradle build' in console. Looks like something wrong with tests for JDK1.7. I ready to reproduce it and sent results to you if it will be need.

**Comment by kelemen** [comment] 2017-01-12 15:29
I'm also building with Java7, so that is not the problem (actually I know that tests used to fail under 1.8 because of a NB test issue).

It would be nice if you could send me those results in whatever way (e.g. email, or link to zip).

**Comment by Apertum** [comment] 2017-01-13 12:36
results of commend 'gradle build' in archieve by link https://drive.google.com/open?id=0B4bXdH90L1ekSUdPNHYzNW5XX0U

**Comment by kelemen** [comment] 2017-01-15 19:43
I think I know what causes the test failures for you. Can you pull the most recent changes (master branch) and see if test passes now?

**Comment by kelemen** [comment] 2017-01-15 22:24
I have noticed that you get two test failures which won't be affected by the changes. What JDK are you using?

**Comment by Apertum** [comment] 2017-01-16 07:34
I pulled latest version. Run 'gradle build':

```
:netbeans-gradle-plugin:jar
:netbeans-gradle-plugin:sourcesJar
:netbeans-gradle-plugin:assemble
:netbeans-gradle-plugin:configureCompileTestJava
:netbeans-gradle-plugin:compileTestJava
Warning: jdk7Compiler property is missing and not compiling with Java 1.7. Using 1.8
warning: [options] bootstrap class path not set in conjunction with -source 1.7
                                                                                warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openid
e.util.NbBundleProcessor' less than -source '1.7'estJava
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.gsf.testrunner.CoreManagerProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.7'
warning: No processor claimed any of these annotations: org.junit.Test,org.netbeans.gradle.project.util.SwingTest,org.junit.Rule,org.junit.Ignore,org.junit.After,org.junit.ClassRul
e,org.junit.Before
4 warnings
:netbeans-gradle-plugin:processTestResources
:netbeans-gradle-plugin:testClasses
:netbeans-gradle-plugin:test

 org.netbeans.gradle.project.properties.ConfigXmlUtilsTest > testSaveDoesNotChangeASingleCharacterTaskArgsHaveValues FAILED
    java.lang.AssertionError at ConfigXmlUtilsTest.java:176ompleted

org.netbeans.gradle.project.properties.ConfigXmlUtilsTest > testSaveDoesNotChangeASingleCharacterTaskArgsHaveNoValues FAILED
    java.lang.AssertionError at ConfigXmlUtilsTest.java:176

257 tests completed, 2 failed, 1 skipped:test > 257 tests completed, 2 failed, 1 skipped
:netbeans-gradle-plugin:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':netbeans-gradle-plugin:test'.
> There were failing tests. See the report at: file:///D:/work/qs/netbeans-gradle-project-master/netbeans-gradle-plugin/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 18.324 secs
```

You right. Where are two failed tests.

My JDK:
```
D:\work\qs\netbeans-gradle-project-master>java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

D:\work\qs\netbeans-gradle-project-master>javac -version
javac 1.8.0_60
```

**Comment by kelemen** [comment] 2017-01-16 18:11
I wonder why I cannot reproduce but this is an old JDK issue: https://bugs.openjdk.java.net/browse/JDK-7150637

I have added a workaround, so tests should no longer fail for you now.

**Comment by Apertum** [comment] 2017-01-17 13:03
I updated Java. everithing is OK now.

```
:netbeans-gradle-plugin:processTestResources UP-TO-DATE
:netbeans-gradle-plugin:testClasses
:netbeans-gradle-plugin:test
:netbeans-gradle-plugin:verifyModuleDependencies
:netbeans-gradle-plugin:check
:netbeans-gradle-plugin:netbeans
Download https://repo1.maven.org/maven2/org/codehaus/mojo/nbm-maven-harness/8.1/nbm-maven-harness-8.1.pom
Download https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/37/mojo-parent-37.pom
Download https://repo1.maven.org/maven2/org/codehaus/mojo/nbm-maven-harness/8.1/nbm-maven-harness-8.1.jar
:netbeans-gradle-plugin:nbm
[ant:makenbm] No updater.jar specified, cannot validate Info.xml against DTD
:netbeans-gradle-plugin:build

BUILD SUCCESSFUL

Total time: 1 mins 48.737 secs

D:\work\qs\netbeans-gradle-project-master>java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

D:\work\qs\netbeans-gradle-project-master>javac -version
javac 1.8.0_112
```

**Closed** 2017-01-17 13:48 UTC
