### ISSUE TITLE
Should I expect completion of Gradle specific DSL in build.gradle?

### ISSUE THREAD

**Issue by gavenkoa** [kelemen/netbeans-gradle-project#322] opened 2017-02-19 07:45 UTC
I found it boring switch between NetBeans editor and https://docs.gradle.org/2.14/dsl/index.html to find proper names for Gradle tasks and supported tasks attributes.

On completion in Netbeans in `build.gradle` file I only get completion for standard Java classes.

Should I expect completion of **Gradle specific DSL** in `build.gradle`?

**Comment by kelemen** [comment] 2017-02-19 12:33
I will consider this as a duplicate of #108.

Anyway, it would be nice but the Groovy editor of NB should be improved for this. Until then I cannot really do much about this.

**Closed by kelemen** 2017-02-19 12:33 UTC
Labels: duplicate
