### ISSUE TITLE
Dependencies and javadoc

### ISSUE THREAD

**Issue by amariottini** [kelemen/netbeans-gradle-project#179] opened 2015-02-05 08:30 UTC
It seems the plugin doesn't download the javadoc of the dependencies (Artifactory accessed as Maven).
Am I missing something?

**Comment by kelemen** [comment] 2015-02-05 08:38
Not very intuitive but you can make the plugin download the javadoc (when you ask it to download dependency sources) by adding this to the build script (of the project whose dependecies' javadoc is to be downloaded):

    apply plugin: 'idea'
    idea.module.downloadJavadoc = true

**Comment by amariottini** [comment] 2015-02-05 13:37
It works with some dependencies and not with others.
For example I have access to Log4j javadoc but not BouncyCastle or my internal libraries.
Any idea?

**Comment by kelemen** [comment] 2015-02-05 15:18
Can you clarify what exactly did you do (and in what order)? (e.g., clicked "Download sources")

**Comment by amariottini** [comment] 2015-02-06 07:12
Changed build.grade.file
Reloaded the project
Downloaded sources

I discovered that only my libraries miss the javadoc (BouncyCastle is ok, my mistake).
Looking at Artifactory I have the -javadoc.jar files (no sources, I don't put sources into Artifactory).
Any idea?

**Comment by kelemen** [comment] 2015-02-06 09:00
Checking at the sources, it seems I have never implemented javadoc lookup when it is downloaded from  a Maven repo (or from whatever into Gradle's cache). If I will have time, I'll add this on the weekend. Though I probably won't have a new release until the Gradle 2.3 problem is fixed.

**Comment by kelemen** [comment] 2015-02-08 21:41
It should now be fixed in master but I have nothing to try this out. It would be great if you could build the plugin from the sources (`gradle build` should be ok) and try if it works for you.

**Comment by amariottini** [comment] 2015-02-09 12:41
I tried and nothing changed.
I tried even to change JAVADOC_SUFFIX = "-javadoc.jar"; (I have javadoc with .jar extension) in the AutoJavaJavadocForBinaryQuery class but doesn't worked.

How can I debug what's happening?

**Comment by kelemen** [comment] 2015-02-09 13:14
".jar" is not needed, the extension is appended.

To debug the project, you need to define the `netBeansExecutable` property in `~/.gradle/gradle.properties` (it is the executable used to start NetBeans).

Anyway, NetBeans should call `GradleCacheJavadocForBinaryQuery.findJavadoc` when it is needed (I guess when you are trying to display the javadoc). So for the purpose of javadoc, this method is the entry point.

**Comment by kelemen** [comment] 2015-02-09 13:17
What it supposed to do is: Assumes that the given binary is in the Gradle cache and (based on some assumption) finds the downloaded javadoc file in the cache.

**Comment by amariottini** [comment] 2015-02-09 13:37
If I manually put the -javadoc.zip file in the cache it is loaded.
If the javadoc file ends with .jar it is not loaded.
I think the plugin should look for .zip and .jar files.....

The problem is the javadoc file is not downloaded and saved in cache when I do Download Sources.

**Comment by kelemen** [comment] 2015-02-09 13:51
Strange because if `idea.module.downloadJavadoc = true` is specified, Gradle should download the javadoc files as well in the particular subproject.

If you put a `-javadoc.zip` file next to it, it is found by another query which is designed for cases when the dependency is commited to the repo.

Anyway, the javadoc file is not supposed to be in the same dir. It must be in its own directory (named after the sha1 code of the file).

**Comment by amariottini** [comment] 2015-02-10 11:00
I verified the -javadoc.jar files are in the Gradle cache.
They are simply not used....

**Comment by kelemen** [comment] 2015-02-10 23:07
I think this issue is now fixed (still, if there are sources, the sources are preferred over javadoc because NB seems to format them nicer).

If you want to build the project from the sources, I recommend cleaning first (because sometimes the Gradle daemon locks some files which will silently not be updated and clean will surely fail if something like this happens). Took me quite a bit of time of wondering why there are misterious method not found errors :).

**Comment by amariottini** [comment] 2015-02-11 17:56
Now it works, thanks.

**Comment by WillBDaniels** [comment] 2015-02-11 18:43
just built this from source, and I can confirm, works awesome. Thanks so much for this! it's great!

**Closed** 2015-02-12 08:49 UTC
Labels: enhancement
