### ISSUE TITLE
Error processing external source paths.

### ISSUE THREAD

**Issue by ExIngus** [kelemen/netbeans-gradle-project#188] opened 2015-03-11 11:39 UTC
If you specify a path to the source files outside the project folder:
sourceSets {main {java{
srcDir  '../BugTestSrc/coreSrc/'
}}}
NetBeans will show errors in these files.
NetBeans will not create new java files in this folder
Gradle Projects compiles without errors.
http://img.techpowerup.org/150311/Capture545-20150311-163352.png
http://img.techpowerup.org/150311/Capture544-20150311-163306.png
Test project:
https://www.dropbox.com/s/vlxhcvmdfoxy8qp/BugTest.zip

Maybe it's the same problem that here https://github.com/kelemen/netbeans-gradle-project/issues/130
NetBeans 8.0.2
Gradle Support 1.3.4
Gradle 2.2.1
Sorry for my bad English.

**Comment by kelemen** [comment] 2015-03-11 12:17
This is a known issue and is not very simple to fix due to how NetBeans works. Also, even if I workaround the problem, you can always expect to have problems where the files of the project are outside of the project directory.

I'm closing this as a duplicate of #130.

**Closed by kelemen** 2015-03-11 12:17 UTC
Labels: duplicate

**Comment by ExIngus** [comment] 2015-03-11 12:28
Sadly. In some projects, it is very useful.
> you can always expect to have problems where the files of the project are outside of the project directory.
Netbeans works correctly with sources located outside the project folder.
Not encountered such a problem in other types of projects.
Gradle also collects correctly.

**Comment by kelemen** [comment] 2015-03-11 12:37
I have just noticed that there is a [workaround method](http://bits.netbeans.org/7.4/javadoc/org-netbeans-modules-projectapi/org/netbeans/api/project/FileOwnerQuery.html#markExternalOwner(org.openide.filesystems.FileObject, org.netbeans.api.project.Project, int)) for this problem in NetBeans. I will probably fix this for the next release.

**Comment by kelemen** [comment] 2015-03-11 12:44
Anyway, I'm currently working on some other problems. If you want it to be fixed quickly, it is pretty simple given the method linked above. You just have to mark all the source directories not in the project directory with `FileOwnerQuery.markExternalOwner` in `JavaExtension.activateExtension` after changing the internal model.
