### ISSUE TITLE
Path base issue in Gradle files

### ISSUE THREAD

**Issue by russel** [kelemen/netbeans-gradle-project#138] opened 2014-05-07 15:20 UTC
The GroovyFX build works fine using Gradle 1.11 on the command line. There is a known problem trying to use Gradle 1.12. The projects Gradle wrapper is 1.11 because of this. Generating an Idea project works and all tests pass. Opening the project in Netbeans leads to a problem in one of the Gradle files. In particular, in the code:

 new File('src/demo/groovy').eachFileMatch(~/.*Demo.groovy/) { file ->

in the file buildSrc/scripts/demo.gradle, the File object is created relative to the location where Netbeans was started rather than relative to the project location. The error Netbeans creates is terminal to the build. :-(

**Comment by eino-makitalo** [comment] 2015-04-02 05:16
This seems to be problem also when running vertx  runMod ( I added main class ) but it expects it to be run in same directory with gradle .build. not it gets IOException becuase trying to create file into directory C:\Program Files\NetBeans 8.0.2\      file to fail is: vertx_classpath.txt

**Comment by kelemen** [comment] 2015-04-02 07:30
I'm closing this as a duplicate of #159. Anyway, relying on the current working directory is wrong in my opinion. You should use use `project.file`. See #159 for details and workaround.

**Closed by kelemen** 2015-04-02 07:30 UTC
Labels: duplicate
