### ISSUE TITLE
Cancelling 'run'/'debug' task sometimes doesn't work

### ISSUE THREAD

**Issue by Barteks2x** [kelemen/netbeans-gradle-project#195] opened 2015-04-15 17:15 UTC
Sometimes when I cancel 'run'/'debug' task it doesn't work (nothing happens, everything isstill open, even after several minutes). The only way to stop it is to manually kill the java process.

**Comment by kelemen** [comment] 2015-04-15 19:28
This plugin only asks Gradle to cancel the task. I'm not sure what it actually does. Anyway, what is your OS? Also, does this happen with both run and debug or only debug?

**Comment by Barteks2x** [comment] 2015-04-15 20:56
It doesn't happen very frequently. I usually only run, but these tasks seem to be very simillar so I assume it also happens with debug task.
I use linux (x)ubuntu 14.10 and oracle java8 (1.8.0_40).

**Comment by Barteks2x** [comment] 2015-04-15 21:00
Usually I cancel task when I can't stop my application normally. I tried to cancel task when it's running normally and it didn't work (the same result with run and debug tasks). I will try to create some simple project that can't be stopped by cancelling task.

**Comment by kelemen** [comment] 2015-04-16 08:17
I have checked in the sources of Gradle and Gradle simply calls `Process.desroy` (there is not much else to do). However, on linux (and similar OS) a process can ignore this call. I would expect this to happen if a shutdown hook fails to terminate for example. Do you - by any chance - have custom shutdown hooks?

**Comment by Barteks2x** [comment] 2015-04-16 10:12
I actually don't know. It's Minecraft related project. Using kill command it stops correctly, but cancelling task doesn't seem to work.

**Comment by kelemen** [comment] 2015-04-16 10:47
Do you also pass "-9" to the kill command?

**Comment by Barteks2x** [comment] 2015-04-16 10:56
No, only "kill <pid>" (SIGTERM).
I also created a simple project with while(true); in main() method. Cancelling 'run' task also didn't work for it.

**Comment by Barteks2x** [comment] 2015-04-16 11:14
Also, I use gradle 2.0 (this project doesn't run with newer version)

**Comment by kelemen** [comment] 2015-04-16 11:28
I guess then that is the problem. Cancellation only works when using Gradle 2.1 or later (note that Gradle 2.3 has a bug which renders many features of this plugin useless).

**Comment by Barteks2x** [comment] 2015-04-16 11:48
It works correctly with gradle 2.1 (I downgraded to 2.0 because that was the version used by gradlew). In some extreme cases I still remember that it failed to stop with gradle 2.4, but in that case the only way to stop it was kill -9, and it isn't possible to do that in java.

**Comment by kelemen** [comment] 2015-04-16 12:05
There is a new `Process.destroyForcibly` in Java 8 but as far as I can see, it does the same thing as `destroy`. Anyway, I don't have access to this process object, so even if `destroyForcibly` works, this can only be fixed in Gradle. Regardless, I will keep this issue open for reference.

**Comment by kelemen** [comment] 2015-04-16 12:14
I was wrong, `Process.destroyForcibly` do forcefully kill the process in Linux. Anyway, this should be updated in Gradle. If you want it, you should report it for the Gradle team (to use `Process.destroyForcibly` in Java 8 to kill the process, possibly only after destroy fails to respond).

**Comment by xtracoder** [comment] 2015-11-22 23:28
I'm experiencing same/similar issues all the time currently (NB 8.1 + Gradle 2.9) after switching from MAVEN to Gradle as build system - after I click button "Finish debugger session" target process keeps running for some rather long time, rather frequently doing unwanted job which requires to be cleaned up manually.

I see following difference from MAVEN 'native' plugin in the processes of starting new debugging session:

1. MAVEN plugin switches Netbeans into debugger listener mode - i see following in console:

NetBeans: JPDA Listening Start...
JPDA Address: EPBYMINW0027:57912

2. Next it calls 'mvn' with arguments "-Dexec.args=\"-Xdebug -Xrunjdwp:transport=dt_socket,server=n,address=57912" - thus saying new process to attach to Netbeans as debugger at startup

What is see is happening in Gradle - target process is started as Xrunjdwp:transport=dt_socket,server=y,address=5005, what actually causes Netbeans to attach to newly started process and in such cases, as far as i notice, Netbeans do not kill target process when closing the debug session - it just detaches from the 'jpda server' process thus letting it run.

May it have sense to start debuggee process similar way as in MAVEN?

**Comment by kelemen** [comment] 2015-11-23 18:47
The current behaviour is that the plugin asks Gradle to cancel the task and Gradle won't react immediately to cancellation requests.

Anyway, what you wrote makes sense but I cannot really change the behaviour because that would be a breaking change (and people would believe debugging got broken). That said, it would be possible to make this configurable. Would that be good for you? Altough, if you have a non-trivial project (i.e., you need to create your own run/debug tasks), the new way of debugging would require more awkward adjustment of your Gradle script (i.e., you would need to manually add those arguments to your run task).

**Comment by xtracoder** [comment] 2015-11-23 20:08
Yes, having it configurable - would be excellent. Will greatly appreciate that.

PS: Another major problem caused by thing that I can't stop target process immediately, is inability to quickly restart the process - because debug port is busy.

**Comment by kelemen** [comment] 2015-12-15 22:00
The new debug mode should now be implemented. You can choose this in the global settings or set it on the project level as well. See the approriate JVM argument configuration in [nb-init-script.gradle](https://github.com/kelemen/netbeans-gradle-project/blob/master/netbeans-gradle-plugin/src/main/resources/org/netbeans/gradle/project/resources/nb-init-script.gradle#L27) if you want to customize your run task.

Notice, that if you switch to "debugger listens", the `run` task will be executed by default instead of the `debug`. This is for better compatibility with the current way of debugging.

Also note that now the *master* branch builds the plugin for NetBeans 8.1 and a new *NetBeans73*  was created for older versions.

**Comment by xtracoder** [comment] 2015-12-16 21:31
Cool, works perfectly - i.e. command "Finish Debugger Session" immediately kills target process.

Many thanks.

**Comment by kelemen** [comment] 2015-12-29 21:19
Improved the "debuggee connects" debugging a little:

- Works with test tasks as well.
- In most cases, you don't need to manually add the JVM arguments ('-Xdebug' etc.). The arguments are added automatically for `Test` and `JavaExec` tasks. However, if you customized any of the debugging tasks (including debug tests), you should add `-PdebuggedTaskName=${project}:run` or `-PdebuggedTaskName=${project}:${test-task-name}` as a task argument (as appropriate).

**Comment by xtracoder** [comment] 2015-12-31 00:44
JFYI: Unfortunately latest changes do not work for me - I think the root cause is bug somewhere deep inside Gradle itself. More details here: https://discuss.gradle.org/t/project-gettasksbyname-causes-stackoverflow/13491, use-case #2

**Comment by xtracoder** [comment] 2015-12-31 01:25
Have got it working after rewriting the code without usage of `findByPath()` like following (without debugging `println` :))

    if (debuggerAttachArgs != null && project.hasProperty('debuggedTaskName')) {
        def taskProject = project
        def debuggedTaskName = project.debuggedTaskName.toString()
        def colonPos = debuggedTaskName.lastIndexOf(':')
        
        if( colonPos >= 0 ) {
            def projectName = debuggedTaskName.substring(0, colonPos)
            taskProject = project.project(projectName)
            debuggedTaskName = debuggedTaskName.substring(colonPos + 1)
        }

        def task = taskProject.tasks.findByName(debuggedTaskName)
        println " ---------- task: " + task + ' in ' + taskProject
        if (task?.project == project) {
            if ((task instanceof JavaExec) || (task instanceof Test)) {
                updateJvmArgs(task, debuggerAttachArgs)
            }
        }
    }}

**Comment by kelemen** [comment] 2015-12-31 02:58
So, you are saying that the current [init script](https://github.com/kelemen/netbeans-gradle-project/blob/master/netbeans-gradle-plugin/src/main/resources/org/netbeans/gradle/project/resources/nb-init-script.gradle) crashing your build script? If that is the case, then it definitely has to be changed.

**Closed** 2016-09-28 09:47 UTC
