### ISSUE TITLE
java.lang.NullPointerException: Argument "initialModule" cannot be null.

### ISSUE THREAD

**Issue by shevek** [kelemen/netbeans-gradle-project#197] opened 2015-04-20 00:50 UTC
```
INFO [org.netbeans.gradle.project.model.SerializedNbGradleModels]: There was a problem when deserializing model for org.netbeans.gradle.project.java.JavaExtension
java.lang.NullPointerException: Argument "initialModule" cannot be null.
        at org.jtrim.utils.ExceptionHelper.checkNotNullArgument(ExceptionHelper.java:467)
        at org.netbeans.gradle.project.java.model.JavaProjectReference.<init>(JavaProjectReference.java:34)
        at org.netbeans.gradle.project.java.model.JavaProjectReference$SerializedFormat.readResolve(JavaProjectReference.java:125)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1104)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1807)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at java.util.HashMap.readObject(HashMap.java:1180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at org.netbeans.gradle.model.util.SerializationUtils.deserializeObject(SerializationUtils.java:69)
[catch] at org.netbeans.gradle.project.model.SerializedNbGradleModels.deserializeModel(SerializedNbGradleModels.java:66)
        at org.netbeans.gradle.project.model.MultiFileModelCache.tryGetModel(MultiFileModelCache.java:36)
        at org.netbeans.gradle.project.model.GradleModelLoader.tryGetFromPersistentCache(GradleModelLoader.java:298)
        at org.netbeans.gradle.project.model.GradleModelLoader.access$400(GradleModelLoader.java:63)
        at org.netbeans.gradle.project.model.GradleModelLoader$5.execute(GradleModelLoader.java:337)
        at org.jtrim.concurrent.AbstractTaskExecutorService$1.execute(AbstractTaskExecutorService.java:142)
        at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
        at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
        at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
        at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:905)
        at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:884)
        at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:798)
        at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:813)
        at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:847)
        at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
        at java.lang.Thread.run(Thread.java:745)
```

Hunting for errors related to #196, not sure if related, but the next log line after this exception was:
```
INFO [org.netbeans.gradle.project.model.GradleModelLoader]: Loading Gradle project from directory: /home/shevek/java/<broken-project>
```

**Comment by shevek** [comment] 2015-04-20 00:51
Same as #166 - I knew I'd seen this before.

**Comment by shevek** [comment] 2015-04-20 01:34
Still happens after cleaning cache and restarting.

**Comment by kelemen** [comment] 2015-04-20 07:38
I'm closing this as a duplicate of #166. Regardless, even though this will (in itself) not cause any serious issues, this error should not happen. Can you send me the files in `<root-project>/.nb-gradle/private/cache`? These files only contain paths and some info parsed from your project (no source of things like that). This might help me solving #196, since it contains all the info NetBeans requires from the build script.

**Closed by kelemen** 2015-04-20 07:38 UTC
