### ISSUE TITLE
SpringLoaded: Hotswapping Classes

### ISSUE THREAD

**Issue by sparkyspider** [kelemen/netbeans-gradle-project#183] opened 2015-02-25 08:51 UTC
I haven't been able to figure out how to "compile on save" using the Gradle plugin so the SpringLoaded java agent can detect the changed classes and hotswap them.

Is this possible without modifying the plugin? If so, can we please put some documentation together. If not, can we update the plugin?

I'm willing to contribute to the development of the Netbeans Gradle Plugin to add this functionality. Also, I don't see an easy way to stop / restart / debug on the server. This would be a nice addition as well as adding support fro Gradle 2.1.

Thoughts appreciated!

**Comment by kelemen** [comment] 2015-02-25 12:00
I have tried - way back then - to implement "compile on save" by running the "classes" task but found that running a Gradle task is too heavy to be executed on save. As far as I know, Maven and Ant projects don't do this, instead they explicitly compile the file. Given that this is prone to so much error, I prefer avoiding this hack. Currently, the best thing you can do is: Define a custom task executing "classes" and run that after you have modified your code and want to apply it (you can use ctrl+F11 to re-run the last execute task). Though I have no plans adding this at the moment, it might be worthwhile to try "compile on save" again (since all the improvements in Gradle, like incremental compilation).

Stop/restart/debug: I don't know how these features should work in NB because I don't use EE and similar. But maybe @hildo's EE plugin might support something like this. Anyway, the general idea is to write your own Gradle tasks and let NB execute them (it does this for simple Java projects as well).

Adding support for Gradle 2.1: What is your problem, as far as I know 2.1 works fine with the plugin.

**Comment by joanasleet** [comment] 2015-03-05 08:24
Is there a possibility to somehow merge the functionalities of 'Save' -> 'Apply Code Changes'   while debugging ? With gradle incremental build it seems to work very well for me - doesn't feel heavy at all (executes in less than a second).

**Comment by kelemen** [comment] 2015-03-05 09:11
It is possible to add this feature, but I don't know a way to add an "on save" task which runs 'Apply Code Changes' just by configuring the IDE. I will consider adding this for the next version.

**Comment by kelemen** [comment] 2015-03-07 16:19
Should be fixed in master and I'll have a new release today due to another serious regression.

**Closed by kelemen** 2015-03-07 16:19 UTC
